# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 306)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sgn = QtWidgets.QTextEdit(self.centralwidget)
        self.sgn.setGeometry(QtCore.QRect(20, 30, 351, 31))
        self.sgn.setObjectName("sgn")
        self.textBtn = QtWidgets.QPushButton(self.centralwidget)
        self.textBtn.setGeometry(QtCore.QRect(590, 32, 141, 31))
        self.textBtn.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.textBtn.setObjectName("textBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.label.setStyleSheet("font: 75 12pt \"MS Sans Serif\";\n"
"")
        self.label.setObjectName("label")
        self.centerText = QtWidgets.QLineEdit(self.centralwidget)
        self.centerText.setGeometry(QtCore.QRect(380, 40, 113, 20))
        self.centerText.setObjectName("centerText")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 61, 16))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.textBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.textBtn_2.setGeometry(QtCore.QRect(590, 102, 141, 31))
        self.textBtn_2.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.textBtn_2.setObjectName("textBtn_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Sans Serif\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.sgn_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.sgn_2.setGeometry(QtCore.QRect(20, 100, 351, 31))
        self.sgn_2.setObjectName("sgn_2")
        self.centerText_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.centerText_2.setGeometry(QtCore.QRect(380, 110, 113, 20))
        self.centerText_2.setObjectName("centerText_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 90, 61, 16))
        self.label_4.setStyleSheet("font: 75 12pt \"MS Sans Serif\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.convBtn = QtWidgets.QPushButton(self.centralwidget)
        self.convBtn.setGeometry(QtCore.QRect(20, 150, 251, 31))
        self.convBtn.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.convBtn.setObjectName("convBtn")
        self.sgn_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.sgn_3.setGeometry(QtCore.QRect(290, 170, 351, 31))
        self.sgn_3.setObjectName("sgn_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 150, 131, 16))
        self.label_6.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.label_6.setObjectName("label_6")
        self.convBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.convBtn_2.setGeometry(QtCore.QRect(20, 190, 251, 31))
        self.convBtn_2.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.convBtn_2.setObjectName("convBtn_2")
        self.convBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.convBtn_3.setGeometry(QtCore.QRect(20, 230, 251, 31))
        self.convBtn_3.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.convBtn_3.setObjectName("convBtn_3")
        self.per1 = QtWidgets.QRadioButton(self.centralwidget)
        self.per1.setGeometry(QtCore.QRect(500, 40, 82, 17))
        self.per1.setObjectName("per1")
        self.per2 = QtWidgets.QRadioButton(self.centralwidget)
        self.per2.setGeometry(QtCore.QRect(500, 110, 82, 17))
        self.per2.setObjectName("per2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(500, 20, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(500, 90, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convolucionador"))
        self.textBtn.setText(_translate("MainWindow", "Visualizar Señal"))
        self.label.setText(_translate("MainWindow", "Señal 1:"))
        self.label_2.setText(_translate("MainWindow", "Centro:"))
        self.textBtn_2.setText(_translate("MainWindow", "Visualizar Señal"))
        self.label_3.setText(_translate("MainWindow", "Señal 2:"))
        self.label_4.setText(_translate("MainWindow", "Centro:"))
        self.convBtn.setText(_translate("MainWindow", "Convolución Finita"))
        self.label_6.setText(_translate("MainWindow", "Señal Resultado:"))
        self.convBtn_2.setText(_translate("MainWindow", "Convolución Periódica"))
        self.convBtn_3.setText(_translate("MainWindow", "Convolución Circular"))
        self.per1.setText(_translate("MainWindow", "Periódica"))
        self.per2.setText(_translate("MainWindow", "Periódica"))
        self.radioButton.setText(_translate("MainWindow", "Finita"))
        self.radioButton_2.setText(_translate("MainWindow", "Finita"))
